src/ResourceRegistry/Configuration/ConsoleTraceService.cs

- updated for identical implementation of ConsoleTraceService across all repos owned by the authorization team
- upgraded altinn-authorization to Yuniql.PostgreSql version to 1.3.15
- #{issue number}

Syncronized implementations of ConsoleTraceService for postgresql version 1.3.15 upgrade

---

src/Altinn.ResourceRegistry.Core/IPolicyRepository.cs
src/Altinn.ResourceRegistry.Core/IResourceRegistry.cs
src/Altinn.ResourceRegistry.Core/ResourceRegistryService.cs
src/Altinn.ResourceRegistry.Persistence/PolicyRepository.cs
src/ResourceRegistry/Controllers/ResourceController.cs
test/ResourceRegistryTest/Data/ResourcePolicies/altinn_access_management/resourcepolicy.xml
test/ResourceRegistryTest/Mocks/PolicyRepositoryMock.cs
test/ResourceRegistryTest/Mocks/RegisterResourceRepositoryMock.cs
test/ResourceRegistryTest/ResourceControllerTest.cs
test/ResourceRegistryTest/ResourceRegistryTest.csproj

Added endpoint for PRP retriavel for resource policy

Added resource registry prp endpoint

---

src/Altinn.ResourceRegistry.Core/Models/CompetentAuthority.cs

Added name property to competent authority model

---

src/Altinn.ResourceRegistry.Core/Clients/AccessManagementClient.cs
src/Altinn.ResourceRegistry.Core/Configuration/PlatformSettings.cs
src/ResourceRegistry/Program.cs
src/ResourceRegistry/appsettings.json
test/ResourceRegistryTest/AccessManagementClientTest.cs

Cleanup appsettings.json and sync with values.yaml
- Renamed accessmanagement API endpoint config value to match naming convention used by other endpoints in PlatformSettings
- Removed hardcoded environment variables and have created PR for setting correct enviromnent values in altinn-studio-ops repo
- #117

Cleanup appsettings.json and sync with values.yaml

---

src/Altinn.ResourceRegistry.Core/Constants/AltinnXacmlConstants.cs
src/ResourceRegistry/Altinn.ResourceRegistry.csproj
test/ResourceRegistryTest/Data/ResourcePolicies/altinn_access_management.xml
test/ResourceRegistryTest/Data/ResourcePolicies/altinn_access_management/resourcepolicy.xml
test/ResourceRegistryTest/Data/ResourcePolicies/altinn_access_management_invalid_missing_resourceid.xml
test/ResourceRegistryTest/Data/ResourcePolicies/altinn_access_management_invalid_resourceid.xml
test/ResourceRegistryTest/Data/ResourcePolicies/altinn_access_management_skd.xml

Updated urn:altinn:resourceregistry to urn:altinn:resource
Deploy need to be synced with PDP and AM 
#149

Changed resourceid for resource registry

---

src/Altinn.ResourceRegistry.Core/Enums/ResourceType.cs
src/Altinn.ResourceRegistry.Core/Services/ResourceRegistryService.cs
src/ResourceRegistry/Controllers/ResourceController.cs

Fixed nullpointer for export and new resource types

Fixed nullpointer for export and new resource types

---

src/ResourceRegistry/Utils/RdfUtil.cs

Null pointer check for uri

---

src/ResourceRegistry/Controllers/ResourceController.cs

Policy creation formatter fix

---

src/Altinn.ResourceRegistry.Persistence/ResourceRegistryRepository.cs

Updated SQL to removed the includeExpired column

Removed expired

---

src/Altinn.ResourceRegistry.Core/Enums/ResourcePartyType.cs

Fixed enum serlization to text

Fixed enum serialization

---

src/Altinn.ResourceRegistry.Core/Models/ServiceResource.cs

Added version

---

src/Altinn.ResourceRegistry.Core/Services/IAltinn2Services.cs
src/Altinn.ResourceRegistry.Integration/Clients/Altinn2ServicesClient.cs
src/ResourceRegistry/Controllers/Altinn2ExportController.cs
test/ResourceRegistryTest/Altinn2ExportControllerTest.cs
test/ResourceRegistryTest/Mocks/Altinn2ServicesClientMock.cs

Added export endpoints for Altinn 2.
To be used by Altinn Studio in resource registry

Added proxy for export for bridge

---

src/ResourceRegistry/Controllers/Altinn2ExportController.cs

Fixed identifer param for policy export

Added error handling and fixed identifer for policy endpoint

---

src/Altinn.ResourceRegistry.Core/Extensions/DateTimeOffsetExtensions.cs
src/Altinn.ResourceRegistry.Core/Models/HttpDateTimeHeaderValue.cs
test/ResourceRegistryTest/HttpDateTimeHeaderValueTests.cs

feat: HttpDateTimeHeaderValue

---

test/Altinn.ResourceRegistry.TestUtils/AsyncLock.cs
test/Altinn.ResourceRegistry.TestUtils/DbFixture.cs
test/Altinn.ResourceRegistry.TestUtils/Singleton.cs

chore: update db test fixture

---

test/Altinn.ResourceRegistry.TestUtils/AdvanceableTimeProvider.cs
test/ResourceRegistryTest/WebApplicationFixture.cs

chore: add advanceable time provider to test utils

---

src/ResourceRegistry/Models/Opaque.cs
src/ResourceRegistry/Utils/Base64UrlEncoder.cs
test/ResourceRegistryTest/Base64UrlEncoderTests.cs
test/ResourceRegistryTest/OpaqueTests.cs

chore: support utf8 byte streams for opaque values

---

src/ResourceRegistry/Results/NotModifiedResult.cs
test/ResourceRegistryTest/Results/NotModifiedResultTests.cs

feat: NotModifiedResult

---

src/Altinn.ResourceRegistry.Core/AccessLists/AccessListLoadOrCreateResult.cs
src/Altinn.ResourceRegistry.Core/AccessLists/IAccessListService.cs
src/Altinn.ResourceRegistry.Core/AccessLists/IAccessListsRepository.cs
src/Altinn.ResourceRegistry.Persistence/AccessListsRepository.ScopedRepository.cs
src/Altinn.ResourceRegistry.Persistence/AccessListsRepository.cs
src/Altinn.ResourceRegistry.Persistence/Aggregates/AccessListAggregate.cs
src/Altinn.ResourceRegistry.Persistence/Aggregates/Aggregate.cs
test/Altinn.ResourceRegistry.Persistence.Tests/AccessListsRepositoryTests.cs

chore: add LoadOrCreateAccessList to AccessListsRepository

---

src/Altinn.ResourceRegistry.Core/Models/Conditional.cs
test/ResourceRegistryTest/JsonPatch/JsonPatchDocumentTests.cs
test/ResourceRegistryTest/JsonPatch/JsonPatchOperationTypeTests.cs
test/ResourceRegistryTest/JsonPatch/JsonPointerTest.cs
test/ResourceRegistryTest/Models/ConditionalTests.cs
test/ResourceRegistryTest/Models/HttpDateTimeHeaderValueTests.cs

feat: Conditional type

---

src/Altinn.ResourceRegistry.Core/Models/Versioned/IVersionEquatable.cs
src/Altinn.ResourceRegistry.Core/Models/Versioned/IVersionedEntityCondition.cs
src/Altinn.ResourceRegistry.Core/Models/Versioned/VersionedEntityConditionResult.cs
test/ResourceRegistryTest/Models/VersionedEntityTests.cs

feat: versioned entities

---

src/ResourceRegistry/JsonPatch/JsonPointer.cs
src/ResourceRegistry/Models/RequestCondition.cs
src/ResourceRegistry/Models/RequestConditionCollection.ModelBinder.cs
src/ResourceRegistry/Models/RequestConditionCollection.cs
src/ResourceRegistry/Program.cs
src/ResourceRegistry/Results/VersionedTaggedObjectResult.cs
test/ResourceRegistryTest/ModelBinding/RequestConditionCollectionModelBinderTests.cs
test/ResourceRegistryTest/Utils/TestWebApplicationFactory.cs

feat: RequestConditionCollection model binding

---

src/Altinn.ResourceRegistry.Core/AccessLists/AccessListService.cs
src/Altinn.ResourceRegistry.Core/AccessLists/IAccessListService.cs
src/Altinn.ResourceRegistry.Core/Models/Versioned/IVersionEquatable.cs
src/Altinn.ResourceRegistry.Core/Models/Versioned/IVersionedEntityCondition.cs
src/ResourceRegistry/Controllers/AccessListsController.cs
src/ResourceRegistry/Models/AccessListInfoDto.cs
src/ResourceRegistry/Models/AggregateVersion.cs
src/ResourceRegistry/Models/ApiDescriptions/ConditionalApiDescriptionProvider.cs
src/ResourceRegistry/Models/ApiDescriptions/ConditionalOperationFilter.cs
src/ResourceRegistry/Models/ITaggedEntity.cs
src/ResourceRegistry/Models/RequestCondition.cs
src/ResourceRegistry/Program.cs
src/ResourceRegistry/Results/ConditionalResult.cs
test/ResourceRegistryTest/AccessListControllerTests.cs
test/ResourceRegistryTest/Results/ConditionalResultTests.cs

chore: create api for access list crud

---

src/Altinn.ResourceRegistry.Core/AccessLists/AccessListIncludes.cs
src/Altinn.ResourceRegistry.Core/AccessLists/AccessListInfo.cs
src/Altinn.ResourceRegistry.Core/AccessLists/AccessListMembership.cs
src/Altinn.ResourceRegistry.Core/AccessLists/AccessListResourceConnection.cs
src/Altinn.ResourceRegistry.Core/AccessLists/AccessListService.cs
src/Altinn.ResourceRegistry.Core/AccessLists/IAccessListAggregate.cs
src/Altinn.ResourceRegistry.Core/AccessLists/IAccessListService.cs
src/Altinn.ResourceRegistry.Core/AccessLists/IAccessListsRepository.cs
src/Altinn.ResourceRegistry.Core/Extensions/SpanExtensions.cs
src/Altinn.ResourceRegistry.Persistence/AccessListsRepository.ScopedRepository.cs
src/Altinn.ResourceRegistry.Persistence/AccessListsRepository.cs
src/Altinn.ResourceRegistry.Persistence/Aggregates/AccessListAggregate.cs
src/ResourceRegistry/Controllers/AccessListsController.cs
src/ResourceRegistry/Models/AccessListInfoDto.cs
src/ResourceRegistry/Models/AccessListResourceConnectionDto.cs
src/ResourceRegistry/Models/ApiDescriptions/AccessListIncludesSchemaFilter.cs
src/ResourceRegistry/Models/ApiDescriptions/SchemaFilter.cs
src/ResourceRegistry/Models/ModelBinding/AccessListIncludesModelBinder.cs
src/ResourceRegistry/Models/ModelBinding/ISingleton.cs
src/ResourceRegistry/Models/ModelBinding/ModelBinder.cs
src/ResourceRegistry/Models/ModelBinding/ModelBinderProviderListExtensions.cs
src/ResourceRegistry/Models/RequestConditionCollection.ModelBinder.cs
src/ResourceRegistry/Program.cs
test/Altinn.ResourceRegistry.Persistence.Tests/AccessListsRepositoryTests.cs
test/ResourceRegistryTest/AccessListControllerTests.cs
test/ResourceRegistryTest/ModelBinding/AccessListIncludesModelBinderTests.cs
test/ResourceRegistryTest/SpanExtensionsTests.cs

feat: access list includes

---

src/Altinn.ResourceRegistry.Core/AccessLists/AccessListService.cs
src/Altinn.ResourceRegistry.Core/AccessLists/IAccessListAggregate.cs
src/Altinn.ResourceRegistry.Core/AccessLists/IAccessListService.cs
src/Altinn.ResourceRegistry.Core/Utils/IConvertibleFrom.cs
src/Altinn.ResourceRegistry.Persistence/Aggregates/AccessListAggregate.cs
src/Altinn.ResourceRegistry.Persistence/Extensions/ResourceRegistryDependencyInjectionExtensions.cs
src/ResourceRegistry/Controllers/AccessListsController.cs
src/ResourceRegistry/Models/AccessListInfoDto.cs
src/ResourceRegistry/Models/AccessListResourceConnectionDto.cs
src/ResourceRegistry/Models/AccessListResourceConnectionWithVersionDto.cs
src/ResourceRegistry/Models/AggregateVersion.cs
test/Altinn.ResourceRegistry.Persistence.Tests/DbTests.cs
test/Altinn.ResourceRegistry.TestUtils/AsyncConcurrencyLimiter.cs
test/Altinn.ResourceRegistry.TestUtils/AsyncLock.cs
test/Altinn.ResourceRegistry.TestUtils/DbFixture.cs
test/ResourceRegistryTest/AccessListControllerTests.cs
test/ResourceRegistryTest/WebApplicationTests.cs

feat: upsert access-list resource-connections

---

src/Altinn.ResourceRegistry.Core/AccessLists/AccessListService.cs
src/Altinn.ResourceRegistry.Core/AccessLists/IAccessListService.cs
src/Altinn.ResourceRegistry.Core/Models/Conditional.cs
src/ResourceRegistry/Controllers/AccessListsController.cs
test/ResourceRegistryTest/AccessListControllerTests.cs
test/ResourceRegistryTest/Models/ConditionalTests.cs
test/ResourceRegistryTest/Results/ConditionalResultTests.cs

feat: delete access-list resource-connection

---

src/Altinn.ResourceRegistry.Persistence/AccessListsRepository.ScopedRepository.cs
src/Altinn.ResourceRegistry.Persistence/ResourceRegistryRepository.cs

chore: prepare statements

---

src/Altinn.ResourceRegistry.Persistence/ResourceRegistryRepository.cs

fix: only prepare when having a dedicated connection

---

src/Altinn.ResourceRegistry/Altinn.ResourceRegistry.csproj

Updated pep package version to 3.0

---

src/Altinn.ResourceRegistry.Core/Helpers/ServiceResourceHelper.cs
src/Altinn.ResourceRegistry/Controllers/ResourceController.cs
test/Altinn.ResourceRegistry.Tests/ResourceControllerTest.cs

Fixed double error handling on same field

Improved validation

---

src/Altinn.ResourceRegistry.Core/Helpers/ServiceResourceHelper.cs
test/Altinn.ResourceRegistry.Tests/ResourceControllerTest.cs

Added emtpy validation

---

src/Altinn.ResourceRegistry/Controllers/ResourceController.cs
test/Altinn.ResourceRegistry.Tests/ResourceControllerTest.cs

feat: add resourcelist filters

---

src/Altinn.ResourceRegistry/Controllers/AccessListsController.cs
src/Altinn.ResourceRegistry/Errors/AltinnProblemDetails.cs
src/Altinn.ResourceRegistry/Extensions/ProblemDetailsExtensions.cs
src/Altinn.ResourceRegistry/JsonPatch/JsonPointer.cs
test/Altinn.ResourceRegistry.Tests/AccessListControllerTests.cs

feat: add error codes to some http errors

---

src/Altinn.ResourceRegistry/Utils/RdfUtil.cs

Added filtering of of apischemes and system resources and testdata

Filter of testdata and api scheme for export

---

src/Altinn.ResourceRegistry.Core/Extensions/AsyncEnumerableExtensions.cs
src/Altinn.ResourceRegistry.Integration/Altinn.ResourceRegistry.Integration.csproj
src/Altinn.ResourceRegistry.Integration/Clients/RegisterClient.cs
src/Altinn.ResourceRegistry.Integration/ResourceRegistryIntegrationDependencyInjectionExtensions.cs
test/Altinn.ResourceRegistry.TestUtils/AsyncList.cs
test/Altinn.ResourceRegistry.Tests/AsyncEnumerableExtensionsTests.cs
test/Altinn.ResourceRegistry.Tests/Integration/RegisterClientTests.cs

fix: split register requests

---

src/Altinn.ResourceRegistry/Program.cs

feat: x-forwarded headers support

---

src/Altinn.ResourceRegistry/Program.cs

feat: x-forwarded headers v2 + logging

---

src/Altinn.ResourceRegistry/Program.cs

feat: fix forwarded logging

---

src/Altinn.ResourceRegistry/Program.cs

fix: less logging

---

src/Altinn.ResourceRegistry.Core/Altinn.ResourceRegistry.Core.csproj
src/Altinn.ResourceRegistry.Core/Errors/Result.cs
src/Altinn.ResourceRegistry/Altinn.ResourceRegistry.csproj
src/Altinn.ResourceRegistry/Controllers/AccessListMembershipsController.cs
src/Altinn.ResourceRegistry/Controllers/AccessListsController.cs

chore: update to ProblemDetails v2

---

src/Altinn.ResourceRegistry/Program.cs
src/Altinn.ResourceRegistry/RequestForwarderLogMiddleware.cs

chore: log more request info

---

src/Altinn.ResourceRegistry/Program.cs

chore: log more forwarded headers

---

Directory.Packages.props
src/Altinn.ResourceRegistry/Altinn.ResourceRegistry.csproj
src/Altinn.ResourceRegistry/Program.cs

chore: add service-defaults

---

src/Altinn.ResourceRegistry/Configuration/CustomTelemetryInitializer.cs

chore: write rolename to stdout

---

src/Altinn.ResourceRegistry/Program.cs

fix: app instights registration bug

---

src/Altinn.ResourceRegistry/Program.cs
src/Altinn.ResourceRegistry/TempExtensions.cs

fix: cleanup bug

---

src/Altinn.ResourceRegistry/Program.cs

chore: re-enable logging

---

src/Altinn.ResourceRegistry/Program.cs
src/Altinn.ResourceRegistry/TempExtensions.cs
src/Altinn.ResourceRegistry/appsettings.Development.json
src/Altinn.ResourceRegistry/appsettings.json

chore: move logging config to configuration

---

src/Altinn.ResourceRegistry/Program.cs
src/Altinn.ResourceRegistry/ResourceRegistryHost.cs
test/Altinn.ResourceRegistry.TestUtils/Altinn.ResourceRegistry.TestUtils.csproj
test/Altinn.ResourceRegistry.Tests/AccessListControllerTests.cs
test/Altinn.ResourceRegistry.Tests/AccessListMembershipsControllerTests.cs
test/Altinn.ResourceRegistry.Tests/Results/ConditionalResultTests.cs

chore: move host configuration to separate class

---

src/Altinn.ResourceRegistry/TempExtensions.cs

chore: remove SetBasePath

---

src/Altinn.ResourceRegistry/Controllers/Altinn2ExportController.cs
src/Altinn.ResourceRegistry/appsettings.json
test/Altinn.ResourceRegistry.Tests/Altinn2ExportControllerTest.cs

Changed authenticaiton from Platformtoken to maskinporten token

Changed authenticaiton for export functionality to maskinporten

---

test/Bruno/Altinn.ResourceRegistry/AccessLists/Get access list members.bru
test/Bruno/Altinn.ResourceRegistry/TestToolsTokenGenerator.js
test/Bruno/Altinn.ResourceRegistry/environments/AT22.bru
test/Bruno/Altinn.ResourceRegistry/environments/Local.bru

chore: bruno updates

---

src/Altinn.ResourceRegistry.Core/Constants/AuthzConstants.cs
src/Altinn.ResourceRegistry.Core/Extensions/AltinnEnumerableExtensions.cs
src/Altinn.ResourceRegistry/Auth/ResourceOwnerExcemptScopesHandler.cs
src/Altinn.ResourceRegistry/Auth/ResourceRegistryAuthAuthorizationServiceCollectionExtensions.cs
src/Altinn.ResourceRegistry/Controllers/AccessListMembershipsController.cs
src/Altinn.ResourceRegistry/ResourceRegistryHost.cs
test/Altinn.ResourceRegistry.Tests/AccessListMembershipsControllerTests.cs

Updated scope to match allowed patterns.

Scope updates

---

src/Altinn.ResourceRegistry.Integration/Clients/Altinn2ServicesClient.cs

Changed query to path

---

src/Altinn.ResourceRegistry.Core/Errors/Problems.cs
src/Altinn.ResourceRegistry.Core/IResourceRegistryRepository.cs
src/Altinn.ResourceRegistry.Core/Models/CompetentAuthority.cs
src/Altinn.ResourceRegistry.Core/Services/Interfaces/IResourceRegistry.cs
src/Altinn.ResourceRegistry.Core/Services/ResourceRegistryService.cs
src/Altinn.ResourceRegistry.Persistence/ResourceRegistryRepository.cs
src/Altinn.ResourceRegistry/Controllers/AccessListsController.cs
test/Altinn.ResourceRegistry.Tests/AccessListControllerTests.cs
test/Altinn.ResourceRegistry.Tests/Mocks/RegisterResourceRepositoryMock.cs
test/Altinn.ResourceRegistry.Tests/WebApplicationTests.cs

feat: validate resource owner when adding connection

---

src/Altinn.ResourceRegistry/ResourceRegistryHost.cs

Added missing service. What kind of noobie error is this.

Fixed missing service

---

src/Altinn.ResourceRegistry/ResourceRegistryHost.cs

Added keyvaultsettings

---

src/Altinn.ResourceRegistry.Integration/Clients/ApplicationsClient.cs

- Filtered away migrated a1/a2 apps
- #{issue number}

Filter migrated a1/a2 apps from resource lists

---

Directory.Packages.props

Updated nugets

---

.github/workflows/build-and-analyze-fork.yml
.github/workflows/build-and-analyze.yml
.github/workflows/codeql-analysis.yml
Directory.Build.props
Directory.Packages.props
Dockerfile
test/Altinn.ResourceRegistry.Tests/Altinn2ExportControllerTest.cs

update to .net 9

---

src/Altinn.ResourceRegistry/Controllers/ResourceController.cs
test/Altinn.ResourceRegistry.Tests/Data/Resources/app_skd_flyttemelding.json
test/Altinn.ResourceRegistry.Tests/ResourceControllerTest.cs

Added fallback to resource list

Added fallback for Altinn apps

---

src/Altinn.ResourceRegistry.Core/Services/Interfaces/IResourceRegistry.cs
src/Altinn.ResourceRegistry.Core/Services/ResourceRegistryService.cs
src/Altinn.ResourceRegistry/Controllers/ResourceController.cs

Added support to download app policies

Added support for app policy
